services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y gfortran libopenblas-dev liblapack-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: your-start-command
