services:
  - type: web
    name: mental-health-chatbot
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9
    disk:
      name: chat-storage
      mountPath: /opt/render/project/src/storage
      sizeGB: 1
